import os
import random
import re
import secrets
import time
from datetime import datetime, timezone, timedelta

KST = timezone(timedelta(hours=9))
import libcommon.config.status_error as status_error
from app.models.response_figure import (
    ReceiptNoRes,
    SetFigureRes,
    SetPostionRes,
    LLMCompletionRes,
    GetReportRes,
    SaveChatRes,
)
from libcommon.utils.chatUtils import get_josa, get_josa_en
from libcommon.utils.jsonUtils import make_json
from app.repositories.session_repository import session_repository

import app.config.app_config as CFG
from app.controllers import chatbot
from app.utils.session_token import generate_session_token, verify_session_token
from app.utils.session_lock import session_locks


def sanitize_filename(name: str) -> str:
    """Remove path separators, dangerous characters, and whitespace from filename."""
    if not name:
        return ""
    return re.sub(r'[/\\<>:"|?*\x00-\x1f\s]', '', name)


card_directions = {
    "강아지": "left",
    "개": "left",
    "개구리": "left",
    "고슴도치": "left",
    "공룡": "left",
    "나비": "left",
    "도마뱀": "left",
    "독수리": "right",
    "돌": "right",
    "돌고래": "left",
    "돼지": "left",
    "말": "right",
    "뱀": "left",
    "병아리": "left",
    "불곰": "right",
    "사자": "right",
    "상어": "right",
    "새끼-양": "left",
    "악어": "left",
    "알에서-나오는-병아리": "left",
    "양": "left",
    "일반-새": "left",
    "젖소": "right",
    "조개": "right",
    "캥거루": "left",
    "코끼리": "right",
    "코브라": "left",
    "토끼": "left",
    "학": "left",
    "호랑이": "right",
    "흑표범": "right",
    "새끼팬더": "left",
}


def _generate_login_code():
    """Generate a unique 6-character alphanumeric code (with DB duplicate check)"""
    import string as _string
    from app.database.mongodb import get_login_codes_collection
    chars = _string.ascii_uppercase + _string.digits
    codes_col = get_login_codes_collection()
    for _ in range(100):
        code = ''.join(random.choices(chars, k=6))
        if not codes_col.find_one({"code": code}):
            return code
    return ''.join(random.choices(chars, k=6))  # fallback


def create_receipt_number(counselor: dict, kid: dict, agree: bool, counselor_email: str = None):
    """Create a new therapy session with unique receipt number"""
    receipt_no = str(secrets.randbelow(9 * 10**15) + 10**15)  # 16-digit random number
    # Strip whitespace from kid name
    if "name" in kid:
        kid["name"] = kid["name"].strip()
    josa = get_josa_en(kid["name"])

    # Generate a login code for session resume
    login_code = _generate_login_code()

    # Create session data
    session_data = {
        "date": datetime.strftime(datetime.now(), format="%Y%m%d%H%M%S"),
        "receiptNo": receipt_no,
        "counselor": counselor,
        "counselorEmail": counselor_email,
        "kid": {**kid, **josa},
        "agree": agree,
        "figures": {"1": [], "2": [], "3": [], "5": [], "6": []},
        "positions": {},
        "friendly_message": "",
        "llmCompletion": {},
        "abuser": {},
        "score": 0,
        "abuse": {"1": 0, "2": 0, "3": 0, "4": 0, "6": 0},
        "report": "",
        "scripts": {},
        "chatHistory": [],
        "loginCode": login_code,
    }

    # Save to JSON first (before MongoDB adds datetime objects)
    sanitized_name = sanitize_filename(kid['name'])
    json_path = os.path.join(CFG.THERAPY_RESULT_DIR, f"{receipt_no}_{sanitized_name}.json")
    make_json(json_path, session_data)

    # Save to MongoDB (this adds datetime fields)
    session_repository.create_session(session_data)

    # Save login code to login_codes collection for resume support
    try:
        from app.database.mongodb import get_login_codes_collection
        codes_col = get_login_codes_collection()
        codes_col.insert_one({
            "code": login_code,
            "counselorEmail": counselor_email or "",
            "counselorName": counselor.get("name", ""),
            "organization": counselor.get("organization", ""),
            "used": True,
            "usedAt": datetime.now(),
            "sessionReceiptNo": receipt_no,
            "createdAt": datetime.now(),
            "autoGenerated": True,
        })
    except Exception as e:
        print(f"Warning: Failed to save login code: {e}")

    session_token = generate_session_token(receipt_no)
    return status_error.OK, ReceiptNoRes(receiptNo=int(receipt_no), endWord=josa, loginCode=login_code, sessionToken=session_token)


def set_figure(kidName: str, receiptNo: int, stage: str, figures: list, family_members: list = None):
    """Set figure selection for a stage"""
    receipt_no_str = str(receiptNo)

    with session_locks.get_sync_lock(receipt_no_str):
        return _set_figure_locked(kidName, receiptNo, receipt_no_str, stage, figures, family_members)


def _set_figure_locked(kidName: str, receiptNo: int, receipt_no_str: str, stage: str, figures: list, family_members: list = None):
    # Get session from MongoDB
    session = session_repository.find_by_receipt_no(receipt_no_str)

    if not session:
        return status_error.BAD_REQUEST, SetFigureRes(score=0)

    if stage in ["3", "5", "6"]:
        family_list = [x["relation"] for x in session["figures"][stage]]
        for figure in figures:
            if figure["relation"] in family_list:
                idx = family_list.index(figure["relation"])
                session["figures"][stage][idx] = figure
            else:
                session["figures"][stage].append(figure)
    else:
        session["figures"][stage] = figures

    # Update MongoDB
    session_repository.update_figures(receipt_no_str, stage, session["figures"][stage])

    # Save family_members if provided (Stage 2 confirm 시점)
    if family_members is not None and isinstance(family_members, list):
        session_repository.update_session(receipt_no_str, {"family_members": family_members})

    score, message = chatbot.get_score(kidName, receiptNo)

    return status_error.OK, SetFigureRes(score=score)


def set_position(kidName: str, receiptNo: int, centerH: int, centerV: int, figures: list, canvas_image: str = None, doll_instances: list = None):
    """Set card positions"""
    if not figures or len(figures) == 0:
        return status_error.BAD_REQUEST, SetPostionRes(score=0, message="인형 배치 데이터가 비어있습니다.")

    receipt_no_str = str(receiptNo)

    # Get session from MongoDB
    session = session_repository.find_by_receipt_no(receipt_no_str)

    if not session:
        return status_error.BAD_REQUEST, SetPostionRes(score=0, message="")

    positions_data = {
        "centerH": centerH,
        "centerV": centerV,
        "figures": figures
    }

    # Process card directions
    for i, card in enumerate(positions_data["figures"]):
        if card["figure"] in card_directions.keys():
            if card["direction"] == 0:
                positions_data["figures"][i]["direction"] = card_directions[card["figure"]]
            else:
                if card_directions[card["figure"]] == "right":
                    positions_data["figures"][i]["direction"] = "left"
                else:
                    positions_data["figures"][i]["direction"] = "right"
        else:
            positions_data["figures"][i]["direction"] = "left"

    session["positions"] = positions_data

    # Update MongoDB
    session_repository.update_positions(receipt_no_str, positions_data)

    # Save canvas image if provided
    if canvas_image:
        session_repository.update_canvas_image(receipt_no_str, canvas_image)
        session["canvasImage"] = canvas_image

    # Save 3D doll instances if provided
    if doll_instances:
        session["dollInstances"] = doll_instances
        session_repository.update_session(receipt_no_str, {"dollInstances": doll_instances})

    # Mark session as completed
    session_repository.update_session(receipt_no_str, {"status": "completed"})

    score, message = chatbot.get_score(kidName, receiptNo)

    return status_error.OK, SetPostionRes(score=score, message=message)


async def llm_completion(kidName: str, receiptNo: int, count: int, relation: str, message: str):
    """Handle LLM chat completion"""
    receipt_no_str = str(receiptNo)

    async with session_locks.get_async_lock(receipt_no_str):
        return await _llm_completion_locked(kidName, receiptNo, receipt_no_str, count, relation, message)


async def _llm_completion_locked(kidName: str, receiptNo: int, receipt_no_str: str, count: int, relation: str, message: str):
    # Get session from MongoDB
    session = session_repository.find_by_receipt_no(receipt_no_str)

    if not session:
        return status_error.BAD_REQUEST, LLMCompletionRes(message="")

    if relation not in session.get("llmCompletion", {}).keys():
        session.setdefault("llmCompletion", {})[relation] = {"bot": ["", ""], "user": ["", ""]}
        session.setdefault("abuser", {})[relation] = 0

        # Update MongoDB
        session_repository.update_llm_completion(receipt_no_str, relation, {"bot": ["", ""], "user": ["", ""]})
        session_repository.update_session(receipt_no_str, {f"abuser.{relation}": 0})

    if count > 0:
        user_messages = session["llmCompletion"][relation]["user"]
        while len(user_messages) < count:
            user_messages.append("")
        user_messages[count - 1] = message

        # Update MongoDB with user message
        session_repository.update_llm_completion(receipt_no_str, relation, session["llmCompletion"][relation])

        # Add to chat history
        chat_entry = {
            "role": "user",
            "relation": relation,
            "content": message,
            "timestamp": datetime.now(KST).isoformat()
        }
        session_repository.update_chat_history(receipt_no_str, chat_entry)

    # Get LLM completion
    completion = await chatbot.get_llm_completion(kidName, receiptNo, count, relation)

    # Update bot message in llmCompletion structure
    bot_messages = session["llmCompletion"][relation]["bot"]
    while len(bot_messages) <= count:
        bot_messages.append("")
    bot_messages[count] = completion
    
    # Update MongoDB with bot message
    session_repository.update_llm_completion(receipt_no_str, relation, session["llmCompletion"][relation])

    # Convert chat history entry
    bot_entry = {
        "role": "bot",
        "relation": relation,
        "content": completion,
        "timestamp": datetime.now(KST).isoformat()
    }
    session_repository.update_chat_history(receipt_no_str, bot_entry)

    return status_error.OK, LLMCompletionRes(message=completion)



def get_Report(kidName: str, receiptNo: int):
    """Get the final report"""
    receipt_no_str = str(receiptNo)

    score, _ = chatbot.get_score(kidName, receiptNo)
    message, data_json = chatbot.get_report(kidName, receiptNo)

    # Remove MongoDB ObjectId (not JSON serializable)
    data_json.pop("_id", None)

    # 신뢰도 분석
    reliability = chatbot.get_reliability(kidName, receiptNo)
    data_json["reliability"] = reliability

    # Update MongoDB with final report
    session_repository.update_report(receipt_no_str, message)
    session_repository.update_scoring(receipt_no_str, score, data_json.get("abuse", {}), data_json.get("abuser", {}), data_json.get("tension"), reliability)

    return status_error.OK, GetReportRes(score=score, message=message, result=data_json)



def save_chat(kidName: str, receiptNo: int, role: str, content: str, relation: str = None):
    """Save a chat message to history"""
    receipt_no_str = str(receiptNo)

    with session_locks.get_sync_lock(receipt_no_str):
        return _save_chat_locked(receipt_no_str, role, content, relation)


def _save_chat_locked(receipt_no_str: str, role: str, content: str, relation: str = None):
    # Verify session exists
    session = session_repository.find_by_receipt_no(receipt_no_str)
    if not session:
        return status_error.BAD_REQUEST, SaveChatRes(success=False)

    chat_entry = {
        "role": role,
        "content": content,
        "timestamp": datetime.now(KST).isoformat()
    }
    if relation:
        chat_entry["relation"] = relation

    # Update MongoDB
    session_repository.update_chat_history(receipt_no_str, chat_entry)

    return status_error.OK, SaveChatRes(success=True)
